### ISSUE TITLE
requirements.txt冲突 & 疑似numpy文件缺失

### ISSUE THREAD

**Issue by yy35959199** [jerryuhoo/VTuberTalk#3]
python试过3.8.10和3.9.7，使用pip install -r .\requirements.txt时报错如下：

ERROR: Cannot install numpy==1.20.0 and spleeter==2.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.20.0
    spleeter 2.3.0 depends on numpy<1.20.0 and >=1.16.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

我看了一下，requirements.txt中还特意指定了spleeter==2.3.0和numpy==1.20.0……这两个是有冲突吗？
尝试通过删除requirements.txt中指定的版本号来解决，最终下载的版本：
spleeter == 2.3.0
numpy == 1.19.3
tensorflow == 2.5.0

但是在执行run_preprocess.sh时，在执行到spleeter时报错：
spleeter
Traceback (most recent call last):
  File "D:\Environment\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Environment\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Environment\Anaconda3\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "D:\Environment\Anaconda3\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    import scipy.ndimage
  File "D:\Environment\Anaconda3\lib\site-packages\scipy\ndimage\__init__.py", line 153, in <module>
    from .interpolation import *
  File "D:\Environment\Anaconda3\lib\site-packages\scipy\ndimage\interpolation.py", line 37, in <module>
    from scipy import special
  File "D:\Environment\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 643, in <module>
    from . import _ufuncs
ImportError: DLL load failed while importing _ufuncs: 找不到指定的模块。

自行查询时，有帖子说是pip下载的numpy中缺少mkl，但是手动将numpy改为1.19.3+mkl版本后，执行结果仍然是这个报错OTZ
目前没有找到进一步的解决方案

**Comment by yy35959199** [comment]
现在卡死在ImportError: DLL load failed while importing _ufuncs: 找不到指定的模块。这里了
环境：
python 3.8.10/3.9.7
都是从头建的虚拟环境，创建anaconda环境之后，只装了飞桨2.2的pip命令和pip install -r .\requirements.txt
cuda本地装的是11.5，但是看飞桨下载的时候应该自动装了11.2和对应的cudnn
所以应该不存在和其他预先安装的包冲突的问题……

**Comment by jerryuhoo** [comment]
requirements.txt里确实是冲突的，原因是paddlepaddle的环境和spleeter还有MFA的环境用到的包的版本都不同，目前requirements.txt应该还用不了，我的建议是你可以先安装完spleeter再手动装一个numpy==1.20.0的版本

**Comment by yy35959199** [comment]
试过了，现在是spleeter2.3.0+numpy 1.20.0，报错还是一样：
spleeter
Traceback (most recent call last):
  File "D:\Environment\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Environment\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Environment\Anaconda3\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "D:\Environment\Anaconda3\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "D:\Environment\Anaconda3\lib\site-packages\librosa\util\utils.py", line 6, in <module>
    import scipy.ndimage
  File "D:\Environment\Anaconda3\lib\site-packages\scipy\ndimage\__init__.py", line 153, in <module>
    from .interpolation import *
  File "D:\Environment\Anaconda3\lib\site-packages\scipy\ndimage\interpolation.py", line 37, in <module>
    from scipy import special
  File "D:\Environment\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 643, in <module>
    from . import _ufuncs
ImportError: DLL load failed while importing _ufuncs: 找不到指定的模块。

考虑到之前1.19.3+mkl也是同样的报错，所以应该不是缺mkl的问题OTZ

**Comment by jerryuhoo** [comment]
你试试先把环境删了，再重装一下，我最新改了一下requirements，可以参照readme再重装一下
```
conda remove -n <envname> --all
```

**Comment by yy35959199** [comment]
重装过了，现在报错是：

spleeter
Traceback (most recent call last):
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[{{node conv2d/Conv2D}}]]
         [[strided_slice_21/_607]]
  (1) Not found: No algorithm worked!
         [[{{node conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Environment\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Environment\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Environment\Anaconda3\Scripts\spleeter.exe\__main__.py", line 7, in <module>
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "D:\Environment\Anaconda3\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Environment\Anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\__main__.py", line 128, in separate
    separator.separate_to_file(
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\separator.py", line 319, in separate
    return self._separate_tensorflow(waveform, audio_descriptor)
  File "D:\Environment\Anaconda3\lib\site-packages\spleeter\separator.py", line 301, in _separate_tensorflow
    prediction = next(prediction_generator)
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 631, in predict
    preds_evaluated = mon_sess.run(predictions)
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 775, in run
    return self._sess.run(
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1280, in run
    return self._sess.run(
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1385, in run
    raise six.reraise(*original_exc_info)
  File "D:\Environment\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1370, in run
    return self._sess.run(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1438, in run
    outputs = _WrappedSession.run(
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1201, in run
    return self._sess.run(*args, **kwargs)
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "D:\Environment\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[node conv2d/Conv2D (defined at \lib\site-packages\spleeter\model\functions\unet.py:109) ]]
         [[strided_slice_21/_607]]
  (1) Not found: No algorithm worked!
         [[node conv2d/Conv2D (defined at \lib\site-packages\spleeter\model\functions\unet.py:109) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node conv2d/Conv2D:
 strided_slice_3 (defined at \lib\site-packages\spleeter\model\__init__.py:305)

Input Source operations connected to node conv2d/Conv2D:
 strided_slice_3 (defined at \lib\site-packages\spleeter\model\__init__.py:305)

Original stack trace for 'conv2d/Conv2D':
  File "\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\Scripts\spleeter.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "\lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "\lib\site-packages\spleeter\__main__.py", line 128, in separate
    separator.separate_to_file(
  File "\lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "\lib\site-packages\spleeter\separator.py", line 319, in separate
    return self._separate_tensorflow(waveform, audio_descriptor)
  File "\lib\site-packages\spleeter\separator.py", line 301, in _separate_tensorflow
    prediction = next(prediction_generator)
  File "\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 612, in predict
    estimator_spec = self._call_model_fn(features, None, ModeKeys.PREDICT,
  File "\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "\lib\site-packages\spleeter\model\__init__.py", line 568, in model_fn
    return builder.build_predict_model()
  File "\lib\site-packages\spleeter\model\__init__.py", line 516, in build_predict_model
    tf.estimator.ModeKeys.PREDICT, predictions=self.outputs
  File "\lib\site-packages\spleeter\model\__init__.py", line 318, in outputs
    self._build_outputs()
  File "\lib\site-packages\spleeter\model\__init__.py", line 499, in _build_outputs
    self._outputs = self._build_output_waveform(self.masked_stfts)
  File "\lib\site-packages\spleeter\model\__init__.py", line 342, in masked_stfts
    self._build_masked_stfts()
  File "\lib\site-packages\spleeter\model\__init__.py", line 465, in _build_masked_stfts
    for instrument, mask in self.masks.items():
  File "\lib\site-packages\spleeter\model\__init__.py", line 336, in masks
    self._build_masks()
  File "\lib\site-packages\spleeter\model\__init__.py", line 432, in _build_masks
    output_dict = self.model_outputs
  File "\lib\site-packages\spleeter\model\__init__.py", line 312, in model_outputs
    self._build_model_outputs()
  File "\lib\site-packages\spleeter\model\__init__.py", line 211, in _build_model_outputs
    self._model_outputs = apply_model(
  File "\lib\site-packages\spleeter\model\functions\unet.py", line 197, in unet
    return apply(apply_unet, input_tensor, instruments, params)
  File "\lib\site-packages\spleeter\model\functions\__init__.py", line 44, in apply
    output_dict[out_name] = function(
  File "\lib\site-packages\spleeter\model\functions\unet.py", line 109, in apply_unet
    conv1 = conv2d_factory(conv_n_filters[0], (5, 5))(input_tensor)
  File "\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 783, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 249, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1012, in convolution_v2
    return convolution_internal(
  File "\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1142, in convolution_internal
    return op(
  File "\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2596, in _conv2d_expanded_batch
    return gen_nn_ops.conv2d(
  File "\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 968, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "\lib\site-packages\tensorflow\python\framework\ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

大概spleeter之后的步骤还是没法执行……但是能自动分割素材还是很感谢您OTZ

**Comment by jerryuhoo** [comment]
我测试了下在我的电脑上运行没有问题，确保在pretrained_models文件夹下有2stems这个模型，这个是spleeter的模型

**Comment by yy35959199** [comment]
我从readme里手动下载了2stems.tar.gz之后将放到目录下，执行sh还是报同样的Not found: No algorithm worked
查看任务管理器之后发现，执行spleeter的瞬间，我的笔记本3050的4G显存瞬间就爆了……
百度之后在https://blog.csdn.net/qq_25837497/article/details/119145467看到说是要手动往py文件里添加限制代码，但是不知道改哪个文件OTZ

**Comment by jerryuhoo** [comment]
在执行之前输入```export TF_FORCE_GPU_ALLOW_GROWTH=true```试试

**Comment by yy35959199** [comment]
这次连报错信息都没有，GPU瞬间100%又回到0%然后结束执行……
目前的数据都拿RX9手动降噪过了，我还是把spleeter这一步跳过去吧OTZ
非常感谢大佬的解答OTZ

**Comment by yy35959199** [comment]
催更！
