### ISSUE TITLE
使用vae训练时报错

### ISSUE THREAD

**Issue by AdamBear** [jerryuhoo/VTuberTalk#8]
use_vae=False时可以正常训练，但是设为true会在打印vae emb之后报如下错误:

`vae emb Tensor(shape=[32, 128], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[ 0.01106150, -0.00533647,  0.02727163, ..., -0.02542805,
          0.04252797, -0.02009230],
        [ 0.02146370, -0.04467753,  0.02303780, ..., -0.01021339,
          0.07281053,  0.05162752],
        [ 0.02097108, -0.01370922,  0.03172483, ..., -0.02364215,
          0.04520676, -0.01360144],
        ...,
        [ 0.01424461, -0.00831835,  0.02734589, ..., -0.03271284,
          0.04211645, -0.01401436],
        [ 0.01376022, -0.01060121,  0.03189645, ..., -0.02554844,
          0.04828957, -0.02037897],
        [ 0.01099866, -0.00934007,  0.03048294, ..., -0.03625970,
          0.04323421, -0.01717222]])
Exception in main training loop: (InvalidArgument) fill_constant(): argument (position 6) must be float, but got NoneType (at /paddle/paddle/fluid/pybind/op_function.h:305)

Traceback (most recent call last):
  File "/mnt/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/mnt/PaddleSpeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 109, in update
    self.update_core(batch)
  File "/mnt/VTuberTalk/train/models/fastspeech2/fastspeech2_updater.py", line 93, in update_core
    if (mu != None):
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 232, in __impl__
    other_var = create_scalar(
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 79, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "/opt/conda/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 73, in create_tensor
    out = _C_ops.fill_constant(out, 'dtype', dtype, 'shape', shape, 'value',
Trainer extensions will try to handle the extension. Then all extensions will finalize.Traceback (most recent call last):
  File "train/exps/fastspeech2/train.py", line 233, in <module>
    main()
  File "train/exps/fastspeech2/train.py", line 229, in main
    train_sp(args, config)
  File "train/exps/fastspeech2/train.py", line 170, in train_sp
    trainer.run()
  File "/mnt/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 198, in run
    six.reraise(*exc_info)
  File "/opt/conda/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/mnt/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/mnt/PaddleSpeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 109, in update
    self.update_core(batch)
  File "/mnt/VTuberTalk/train/models/fastspeech2/fastspeech2_updater.py", line 93, in update_core
    if (mu != None):
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 232, in __impl__
    other_var = create_scalar(
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 79, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "/opt/conda/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 73, in create_tensor
    out = _C_ops.fill_constant(out, 'dtype', dtype, 'shape', shape, 'value',
ValueError: (InvalidArgument) fill_constant(): argument (position 6) must be float, but got NoneType (at /paddle/paddle/fluid/pybind/op_function.h:305)
`

**Comment by jerryuhoo** [comment]
vae还没做好，可以忽略。目前没试出好的效果

**Comment by AdamBear** [comment]
好的，理解，期待进展!
